title: TTBA Group
description: Marketing Agency for Small Business in Montreal
author: Leo Gamalyunov


email: info@ttbagroup.com
url: "https://ttbagroup.github.io"
baseurl: ""
assets: "/assets"
permalink: :title

markdown: kramdown

kramdown:
  parse_span_html: true

defaults:
    - scope:
        path: ""
      values:
        layout: "default"

exclude: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules']
keep_files: ['sftp-config.json', '.htaccess']
include: ['.htaccess']

plugins_dir:
  - jekyll-redirect-from
  - jekyll-feed

prose:
  rooturl: ''
  siteurl: 'http://ttbagroup.github.io'
  media: 'assets'
  ignore: ['CNAME', '_config.yml', '_config-dev.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules']
  metadata:
    pages:
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "Main URL for the page, see <a href='https://jekyllrb.com/docs/permalinks/'>permalinks</a>. It should start and end with /. Only latin chars are allowed."
          type: "text"
          placeholder: "/main-title/"
      - name: "redirect_from"
        field:
          element: "text"
          label: "Redirect URL"
          help: "This URL will redirect to the permalink"
          type: "text"
          placeholder: "/alternative-title/"
      - name: "ref"
        field:
          element: "text"
          label: "Reference"
          help: "Short word to identify the translation of the page in other language"
          type: "text"
          placeholder: "home"
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          help: "Choose page language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Français'
              value: 'fr'
      - name: "tilda"
        field:
          element: "checkbox"
          label: "Tilda"
          value: true
      - name: "transparent"
        field:
          element: "checkbox"
          label: "Transparent header"
          help: "Make header transparent, in case if you have juicy hero or something like that"
          value: false
      - name: "inverse"
        field:
          element: "checkbox"
          label: "Inverse header"
          help: "Turn header into white font, in case if you have dark hero"
          value: false
      - name: "image"
        field:
          element: "text"
          label: "Featured image URL"
          help: "Insert URL to the image used as featured for the post: facebook, pinterest etc"
          type: "text"
          placeholder: "/assets/image.jpg"
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          help: "Title tag. Keywords first, < 70 chars, no articles/preps/etc."
          type: "text"
          placeholder: "[Primary Keyword] - [Secondary Keyword] | TTBA Group | Montreal"
      - name: "meta-description"
        field:
          element: "textarea"
          label: "Meta Description"
          help: "Used as description snippet by search engines. < 160 chars"
          placeholder: ""
      - name: "noindex"
        field:
          element: "checkbox"
          label: "Noindex"
          help: "Block search indexing of the page"
          value: false
      - name: "nofollow"
        field:
          element: "checkbox"
          label: "Nofollow"
          help: "Block crawler following the page"
          value: false
      - name: "boost"
        field:
          element: "checkbox"
          label: "Boost"
          help: "Remove footer and non-cached scripts to allow for 100 page speed insights"
          value: false
      - name: "canonical"
        field:
          element: "text"
          label: "Canonical"
          help: "Canonical link url, if required"
          type: "text"
          placeholder: "https://ttbagroup.com/whatever"
      - name: "previous"
        field:
          element: "text"
          label: "Previous page"
          help: "Permalink or ref to previous page, if relevant"
          placeholder: "/en/prev-case/"
      - name: "next"
        field:
          element: "text"
          label: "Next page"
          help: "Permalink or ref to next page, if relevant"
          placeholder: "/en/next-case/"
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "date"
        field:
          element: "text"
          label: "Publish Date"
          value: ""
          help: "Overrides the date from the name of the post. HH:MM:SS are optional."
          placeholder: "YYYY-MM-DD HH:MM:SS"
          type: "date"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "Main URL for the page, see <a href='https://jekyllrb.com/docs/permalinks/'>permalinks</a>. It should start and end with /. Only latin chars are allowed."
          type: "text"
          placeholder: "/main-title/"
      - name: "redirect_from"
        field:
          element: "text"
          label: "Redirect URL"
          help: "This URL will redirect to this page"
          type: "text"
          placeholder: "/alternative-title/"
      - name: "noindex"
        field:
          element: "checkbox"
          label: "Noindex"
          help: "Block search indexing of the page"
          value: false
      - name: "nofollow"
        field:
          element: "checkbox"
          label: "Nofollow"
          help: "Block crawler following the page"
          value: false
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          help: "Choose post language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Français'
              value: 'fr'
      - name: "ref"
        field:
          element: "hidden"
          value: "blog"
      - name: "tilda"
        field:
          element: "checkbox"
          label: "Tilda"
          value: true
      - name: "transparent"
        field:
          element: "checkbox"
          label: "Transparent header"
          help: "Make header transparent, in case if you have juicy hero or something like that"
          value: false
      - name: "inverse"
        field:
          element: "checkbox"
          label: "Inverse header"
          help: "Make header white, in case if you have dark hero"
          value: false
      - name: "image"
        field:
          element: "text"
          label: "Featured image URL"
          help: "Insert URL to the image used as featured for the post: facebook, pinterest etc"
          type: "text"
          placeholder: "/assets/image.jpg"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          type: "text"
          help: "Personalization matters"
          placeholder: "Leo, is that you?"
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          help: "Title tag. Keywords first, < 70 chars, no articles/preps/etc."
          type: "text"
          placeholder: "[Primary Keyword] - Marketing Blog | TTBA Group | Montreal"
      - name: "meta-description"
        field:
          element: "textarea"
          label: "Meta Description"
          help: "Used as description snippet by search engines. < 160 chars"
          placeholder: ""
      - name: "canonical"
        field:
          element: "text"
          label: "Canonical"
          help: "Canonical link url, if required"
          type: "text"
          placeholder: "https://ttbagroup.com/whatever"
t:
  title:
    en: TTBA Group
    fr: Groupe TTBA
    ru: Группа ТТБА
  description:
    en: Marketing Agency for Small Business in Montreal
    fr: Agence web pour les PME à Montréal
    ru: Маркетинговое агентство для малого бизнеса в Монреале
  languages:
    - name: 'English'
      key: 'en'
    - name: 'Français'
      key: 'fr'
  menu:
    en:
      home: "Agency"
      services: "Services"
      all-services: "All Services"
      blog: "Insights"
      projects: "Our Work"
      about: "About"
      contact: "Contact us"
      design: "Web Design"
      smm: "Social Media"
      seo: "SEO"
      advertising: "Advertising"
      branding: "Branding"
      video: "Video"
      linkedin-lead-gen: "LinkedIn Lead Generation"
      team: "The Team"
      careers: "Careers"
      frontend: "Front-End Developer Position"
      internship: "Internship"
    fr:
      home: "L’Agence"
      services: "Services"
      all-services: "Tous Services"
      projects: "Projets"
      blog: "Blogue"
      about: "À propos"
      contact: "Contact"
      design: "Conception de sites web"
      smm: "Gestion des médias sociaux"
      seo: "Référencement naturel (SEO)"
      advertising: "Publicité en ligne"
      branding: "Branding et graphisme"
      video: "Vidéographie"
      //linkedin-lead-gen: "LinkedIn Lead Generation"
      team: "Équipe"
      careers: "Carrières"
      frontend: "Intégrateur Front End"
      internship: "Stage en médias sociaux"
  copyright:
    en: "© 2017 TTBA Group Inc. All rights reserved.<br>info@ttbagroup.com"
    fr: "© 2017 TTBA Group Inc. All rights reserved.<br>info@ttbagroup.com"
